#!/bin/bash

# @author Frosty-Z
# @date 2015-12-22
# @desc push changes made by 1_process.sh to 'dirtylab.github.io' repo. adapted for Travis-CI.

TMP_DIR="tmp_site"

DEST_REPO="https://$GH_USER:$GH_TOKEN@github.com/dirtylab/dirtylab.github.io"
DEST_DIR="dirtylab.github.io"

if [ ! -d "$DEST_DIR" ]; then
  echo "*** Create $DEST_DIR directory"
  git clone $DEST_REPO
fi

cd $DEST_DIR

git pull

cp -rf ../$TMP_DIR/* .

# may be generated by a local Jekyll
rm -rf _site

git add .

git config user.name "Travis-CI"
git config user.email "travis@ci.com"

git commit -m "commit depuis Travis-CI (build number $TRAVIS_BUILD_NUMBER)"

git push --force --quiet origin master > /dev/null 2>&1