#!/bin/bash

# @author Frosty-Z
# @date 2015-12-22
# @desc push changes made by 1_process.sh to 'dirtylab.github.io' repo. adapted for Travis-CI.

# execution context agnostic
cd "${BASH_SOURCE%/*}" || (echo "FAILURE: impossible de trouver le répertoire courant" ; exit 1)
source_dir=$(pwd)
# include vars
. vars.sh

dest_repo="https://$GH_USER:$GH_TOKEN@$GH_REF"

if [ ! -d "$dest_repo_path" ]; then
  echo "*** Create $dest_repo_path directory"
  mkdir $dest_repo_path
  cd $dest_repo_path
  git init
  git remote add origin $dest_repo
else
  cd $dest_repo_path
fi

git pull origin master

ls $jekyll_tmp_dir

cp -rf $jekyll_tmp_dir/* .

# may be generated by a local Jekyll
rm -rf _site

git config user.name "$GH_USER"
git config user.email "$GH_EMAIL"


git add -A .

git commit -m "commit depuis Travis-CI (build number $TRAVIS_BUILD_NUMBER)"

git push --force --quiet  origin master > /dev/null 2>&1
#pour debug
# git push origin master

# sauvegarde de la référence du dernier commit
[[ ! -d $meta_dir ]] && mkdir $meta_dir
echo $TRAVIS_COMMIT > $last_commit_file